import type { Metadata } from 'next'
import '../styles/global.css';
import { Header } from './components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className='pl-[18rem]'>
        <Header />
        {children}
        </body>
    </html>
  )
}
